apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: manifests/app-of-apps
    repoURL: https://github.com/iaingalloway/home-automation.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
