apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/argocd-namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
patches:
  - path: patches/disable-tls.yaml
  - path: patches/enable-anonymous-access.yaml
  - path: patches/enable-helm.yaml
