apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: home-assistant
spec:
  destination:
    name: in-cluster
    namespace: home-assistant
  project: default
  source:
    path: manifests/apps/home-assistant
    repoURL: https://github.com/iaingalloway/home-automation.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
