apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant

helmCharts:
  - repo: http://pajikos.github.io/home-assistant-helm-chart/
    name: home-assistant
    namespace: home-assistant
    releaseName: home-assistant
    valuesFile: values.yaml
    version: 0.2.45
